### ISSUE TITLE
More prominently remind users to do the challenge

### ISSUE THREAD

**Issue by Josh-Cena** [coursetable/coursetable#1633]
Now we don't require doing the challenge to access catalog data. This means users that aren't pre-verified (via Yalies) and haven't done the challenge are "logged in" but the catalog data still says "log in to see ratings". However, they don't know until they click on something else that needs evals access, such as the worksheet.

This is not good, since we are planning to make worksheets available to all users including those without evals access!

Instead, we should add an alert box telling users that "you are signed in but you need to do the challenge to access evals". I have three ideas:

1. It could be an item shown in the "me" dropdown, and we could add a little exclamation mark.
2. It could be a top-level banner.
3. It could be a popup in the bottom-right corner.

I slightly favor the first idea—because we don't want users to be able to dismiss it, otherwise it will be hard to bring it back up again.

**Comment by benzuzu** [comment]
@Josh-Cena Thoughts on an actual button in this boxed whitespace area? I feel like usability wise it may be better to have something immediately visible rather than hidden in dropdown. I definitely see how options (2) and (3) are a bit too loud if we pop up on every refresh, but option (1) seems too subtle/hard to find.

<img width="1728" alt="Screenshot 2024-03-24 at 6 32 14 PM" src="https://github.com/coursetable/coursetable/assets/71607240/5ed0f658-9e79-4341-9f9b-fe5f64a97327">

**Comment by Josh-Cena** [comment]
Hmmm. Maybe? I don't really know what to expect since like we are talking about a tiny fraction of our users.
