### ISSUE TITLE
Add "No skills" and "No areas" options to skills/areas filter

### ISSUE THREAD

**Issue by joshuachough** [coursetable/coursetable#359]
for the purpose of removing distributional requirements a user is not interested in from a search similar to old coursetable's "None" option

**Comment by hsheth2** [comment]
Huh interesting - can we ask what this would enable them to do? I suspect an “exclude skill/area” option would be more effective, but it might also be too much complexity vs the gain from a UX perspective

**Comment by itsjoshthedeveloper** [comment]
this would enable them to select "No skills" and "Hu" if they didn't want to see "So" or "Sc" credit courses. it seems that this is a better solution than an "exclude skill/area" option because it keeps it all in one dropdown and allows you to exclude more than one (or all) skills and areas. that being said, i don't think this is a highly requested or needed feature.

**Comment by hsheth2** [comment]
What happens if someone selects “no skills” and “QR” at the same time

**Comment by itsjoshthedeveloper** [comment]
that's a good point. my guess would be it would show courses with no skills that have QR but don't have WR or L (like on the old coursetable). but i agree that this does run the risk of getting confusing..

**Comment by Josh-Cena** [comment]
Instead of adding "no skills", we will add negative filters so users can explicitly select "non-Hu courses". Tracking in https://github.com/coursetable/coursetable/issues/1461 instead.
