### ISSUE TITLE
Not all historical courses showing

### ISSUE THREAD

**Issue by kevinhu** [coursetable/coursetable#478]
In certain instances, the course modal does not show all past offerings of a course. For instance, CHEM 175 (Organic Chem for 1st years II) has been offered since before 2017, but the modal for the Spring 2021 offering only displays two such past courses.

One solution might be to switch the modal query to use the `same_course_id` and `same_course_and_profs_id` columns recently added in Ferry, which are now used for average rating calculations. The ID for one course can be used to query all courses with the same ID, which identify them as the same class / same class and same professors, respectively.

Query for "CHEM 175" over the past five years:
<img width="1083" alt="Screen Shot 2021-01-24 at 10 53 09" src="https://user-images.githubusercontent.com/6051736/105635752-9c625d80-5e32-11eb-9af0-bacdf556e653.png">

Course modal for CHEM 175 in Spring 2021:
<img width="316" alt="Screen Shot 2021-01-24 at 10 53 24" src="https://user-images.githubusercontent.com/6051736/105635762-b00dc400-5e32-11eb-9ab4-82117edbf35d.png">

**Comment by achrysaetos** [comment]
Maybe it's because we exclude all the courses without evaluations:
![Screen Shot 2021-03-15 at 11 15 59 PM](https://user-images.githubusercontent.com/51834103/111255479-20d88d80-85e5-11eb-80b2-df1df54f9bea.png)

Chem 175 of '20 had no evaluations because everyone passed due to the pandemic (so they didn't let us do evaluations, if I remember correctly), and Chem 175 of '21 has no evaluations because it's this semester's course. Not sure about Chem 175 of '17, though -- maybe it also has no evaluations for some reason?

One option we may have if we still want to display all the courses without evaluations is that we can still show a season and instructor, but make the button grayed out and unclickable with a tooltip that says "evaluations unavailable". But we'd probably be better off not showing it (which is what Max currently has) because the class/prof/work ratings would all be empty anyway. Any thoughts, @kevinhu ?

**Comment by kevinhu** [comment]
We can be pretty certain that CHEM 175 has a bunch of previous evaluations that are being hidden – the old site shows several previous offerings:
<img width="322" alt="Screen Shot 2021-03-15 at 23 26 57" src="https://user-images.githubusercontent.com/6051736/111265230-0521b700-85e6-11eb-951e-af68bf62a4b2.png">

Checking our database, we can also find the relevant evaluations. In the end, the solution should remain the same – the problem is finding all previous offerings of a course, and that's been mostly solved via the `same_course_id` and `same_course_and_profs_id` columns.

**Comment by achrysaetos** [comment]
We figured out that we don't have a lot of the past evaluations after all -- that's why past courses without evaluations don't show up on the modal.
