### ISSUE TITLE
Hide "enable evaluation" button if already enabled

### ISSUE THREAD

**Issue by hsheth2** [coursetable/coursetable#63]

**Comment by pxpeterxu** [comment]
I was just a bit confused by this initially! Is the scope of this task to:

1. Hide the enable evaluations button only after evaluations are enabled, or
2. Hide the enable evaluations button always?

If it's 1., I thought we already hid it! Do you mean to hide it in the menu too? (That'd make sense!)

![image](https://user-images.githubusercontent.com/2924388/73601299-efe9e600-4513-11ea-99d2-ddaa660b5a3c.png)

If it's 2. (hide it always), we still need the button for now. The “Enable evaluations” button is there because different students (e.g., undergrads, grad students, vs. staff, who also have NetIDs/CAS accounts) have different levels of access, and for now, we only want those who have undergrad access to be able to see evaluations.

Until we have a way to automatically detect whether someone is an undergrad via an API (we used to do this by scraping Yale Phonebook), we probably shouldn’t remove it completely
