### ISSUE TITLE
Extra year 9999 option shown in term selector dropdown

### ISSUE THREAD

**Issue by ErikBoesen** [coursetable/coursetable#72]
<img width="411" alt="" src="https://user-images.githubusercontent.com/5923662/68138804-17bab500-fef7-11e9-8f11-45ba75339f2b.png">

**Comment by kevinhu** [comment]
The issue seems to result from the way that the crawler fetches the semesters that it needs to retrieve course listings. First, it goes to https://courses.yale.edu/ and scrapes the options under the dropdown menu that allows you to specify the course term. 

<img width="449" alt="Screen Shot 2019-11-04 at 4 01 34 PM" src="https://user-images.githubusercontent.com/6051736/68157827-6e86b580-ff1c-11e9-85fd-d856a0397ac1.png">

Here we see that Yale has added a catch-all "Past Terms" option that has a semester code of 999999, which is why the crawler is registering it as year 9999.

**Comment by hsheth2** [comment]
Fixed by hsheth2/coursetable-crawler@3bf31e8e281a46a60d6e8e94b3b6639ea6de3aac.
