### ISSUE TITLE
Evaluations displayed within course info table in modal

### ISSUE THREAD

**Issue by hsheth2** [coursetable/coursetable#93]
Problem does not occur universally - can't isolate to particular machine or browser or type of user. In addition, have not yet found another course besides [PHIL 427](https://coursetable.com/Table/202001/course/PHIL_427_1) for which this occurs.

<img width="1220" alt="Screen Shot 2020-02-08 at 5 23 33 PM" src="https://user-images.githubusercontent.com/31944154/74092837-bd9e3280-4a97-11ea-8cce-c46bb4691956.png">

**Comment by codyjlin** [comment]
<img width="1220" alt="Screen Shot 2020-02-08 at 5 23 33 PM" src="https://user-images.githubusercontent.com/31944154/74092837-bd9e3280-4a97-11ea-8cce-c46bb4691956.png">

Problem does not occur universally - can't isolate to particular machine or browser or type of user. In addition, have not yet found another course for which this occurs.

**Comment by codyjlin** [comment]
Problem does not occur universally - can't isolate to particular machine or browser or type of user. In addition, have not yet found another course for which this occurs.

**Comment by codyjlin** [comment]
Console output for expected behavior vs actual behavior parsing the CourseModal.ejs/tsx into javascript:

<img width="938" alt="Screen Shot 2020-02-08 at 5 26 17 PM" src="https://user-images.githubusercontent.com/31944154/74092865-300f1280-4a98-11ea-95b7-e52d25a9faba.png">

<img width="1012" alt="Screen Shot 2020-02-08 at 5 26 33 PM" src="https://user-images.githubusercontent.com/31944154/74092866-356c5d00-4a98-11ea-9709-11cd78c89e2f.png">

**Comment by codyjlin** [comment]
Discovered that bug is connected to particular users - if "See which friends have taken this" has never been selected before, then evaluations still display in right position, but the javascript is still wrongly parsed:

<img width="1077" alt="Screen Shot 2020-02-22 at 5 41 36 PM" src="https://user-images.githubusercontent.com/31944154/75100391-062b1500-559b-11ea-8d25-5d3d59ac3f55.png">

**Comment by codyjlin** [comment]
Also, it's not possible to debug running coursetable locally, since the issue doesn't appear when not all of the course flags show up that would show up in production.
Currently looking into how we fetch / store these in our database, and if the notes section is even necessary.

<img width="1101" alt="Screen Shot 2020-02-22 at 5 47 09 PM" src="https://user-images.githubusercontent.com/31944154/75100428-5f934400-559b-11ea-8cf9-2c6d27019a47.png">

**Comment by hsheth2** [comment]
Should be fixed by the output sanitation in React.
